"""init

Revision ID: b99db914eb35
Revises: a9097116970a
Create Date: 2026-03-31 15:20:33.704845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b99db914eb35'
down_revision: Union[str, Sequence[str], None] = 'a9097116970a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bussinesType', sa.Enum('it_services', 'healthcare', 'education', 'finance', 'retail', 'real_estate', 'hospitality', 'manufacturing', 'transportation', 'entertainment', name='bussinestype'), nullable=True),
    sa.Column('discount_percentage', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('isDeleted', sa.Integer(), nullable=True),
    sa.Column('isBlocked', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissions_id'), 'commissions', ['id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planId', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('planCode', sa.String(), nullable=True),
    sa.Column('planType', sa.Enum('free', 'paid', name='plantype'), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('period', sa.Enum('default', 'monthly', 'quaterly', 'yearly', name='periodtype'), nullable=True),
    sa.Column('max_requests', sa.Integer(), nullable=True),
    sa.Column('max_calls', sa.Integer(), nullable=True),
    sa.Column('max_messages', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('isDeleted', sa.Integer(), nullable=True),
    sa.Column('isBlocked', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planCode')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_planId'), 'plans', ['planId'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriptionsId', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('planCode', sa.String(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'expired', name='planstatus'), nullable=True),
    sa.Column('planType', sa.Enum('free', 'paid', name='plantype'), nullable=True),
    sa.Column('period', sa.Enum('default', 'monthly', 'quaterly', 'yearly', name='periodtype'), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('used_requests', sa.Integer(), nullable=True),
    sa.Column('used_calls', sa.Integer(), nullable=True),
    sa.Column('used_messages', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('isDeleted', sa.Integer(), nullable=True),
    sa.Column('isBlocked', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planCode'], ['plans.planCode'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_subscriptionsId'), 'subscriptions', ['subscriptionsId'], unique=True)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenantId', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('isDeleted', sa.Integer(), nullable=True),
    sa.Column('isBlocked', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_tenantId'), 'tenants', ['tenantId'], unique=True)
    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('callId', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('caller_number', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('isDeleted', sa.Integer(), nullable=True),
    sa.Column('isBlocked', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_callId'), 'call_logs', ['callId'], unique=True)
    op.create_index(op.f('ix_call_logs_id'), 'call_logs', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversationId', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('call', 'whatsapp', name='soucetype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('isDeleted', sa.Integer(), nullable=True),
    sa.Column('isBlocked', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source')
    )
    op.create_index(op.f('ix_conversations_conversationId'), 'conversations', ['conversationId'], unique=True)
    op.create_index(op.f('ix_conversations_customer_phone'), 'conversations', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leadId', sa.String(), nullable=True),
    sa.Column('tenantId', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('call', 'whatsapp', name='soucetype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('isDeleted', sa.Integer(), nullable=True),
    sa.Column('isBlocked', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_leadId'), 'leads', ['leadId'], unique=True)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_tenantId'), 'leads', ['tenantId'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paymentId', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='paymentstatus'), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('payment_method', sa.Enum('card', 'upi', 'netbanking', name='paymentmethod'), nullable=True),
    sa.Column('userType', sa.Enum('user', 'admin', 'subAdmin', name='usertype'), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('isDeleted', sa.Integer(), nullable=True),
    sa.Column('isBlocked', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_method'),
    sa.UniqueConstraint('status'),
    sa.UniqueConstraint('transaction_id'),
    sa.UniqueConstraint('userType')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_paymentId'), 'payments', ['paymentId'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('messageId', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.Enum('user', 'ai_agent', name='sendertype'), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('isDeleted', sa.Integer(), nullable=True),
    sa.Column('isBlocked', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_messageId'), 'messages', ['messageId'], unique=True)
    op.add_column('session', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('session', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('session', sa.Column('isDeleted', sa.Integer(), nullable=True))
    op.add_column('session', sa.Column('isBlocked', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session', 'users', ['userId'], ['id'])
    op.add_column('users', sa.Column('userId', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('firstName', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lastName', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('isEmailVerified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('emailExpireAt', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('isPhoneVerified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phoneExpireAt', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('isProfileComplete', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('description', sa.String(), nullable=True))
    op.add_column('users', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('isDeleted', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('isBlocked', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index(op.f('ix_users_userId'), 'users', ['userId'], unique=True)
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_foreign_key(None, 'users', 'subscriptions', ['subscription_id'], ['id'])
    op.create_foreign_key(None, 'users', 'plans', ['plan_id'], ['id'])
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('users', 'name')
    op.drop_column('users', 'createdAt')
    op.drop_column('users', 'updatedAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updatedAt', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('createdAt', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_userId'), table_name='users')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.drop_column('users', 'isBlocked')
    op.drop_column('users', 'isDeleted')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'subscription_id')
    op.drop_column('users', 'plan_id')
    op.drop_column('users', 'description')
    op.drop_column('users', 'isProfileComplete')
    op.drop_column('users', 'phoneExpireAt')
    op.drop_column('users', 'isPhoneVerified')
    op.drop_column('users', 'emailExpireAt')
    op.drop_column('users', 'isEmailVerified')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    op.drop_column('users', 'tenant_id')
    op.drop_column('users', 'userId')
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'isBlocked')
    op.drop_column('session', 'isDeleted')
    op.drop_column('session', 'updated_at')
    op.drop_column('session', 'created_at')
    op.drop_index(op.f('ix_messages_messageId'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_payments_paymentId'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_leads_tenantId'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_leadId'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_phone'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_conversationId'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_call_logs_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_callId'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_index(op.f('ix_tenants_tenantId'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_subscriptions_subscriptionsId'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_plans_planId'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_commissions_id'), table_name='commissions')
    op.drop_table('commissions')
    # ### end Alembic commands ###
